/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// QuantityType the model 'QuantityType'
type QuantityType string

// List of QuantityType
const (
	QUANTITYTYPE_ALL_SHARES QuantityType = "ALL_SHARES"
	QUANTITYTYPE_DOLLARS QuantityType = "DOLLARS"
	QUANTITYTYPE_SHARES QuantityType = "SHARES"
)
