/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// WatchlistInstrument struct for WatchlistInstrument
type WatchlistInstrument struct {
	Symbol string `json:"symbol,omitempty"`
	Description string `json:"description,omitempty"`
	AssetType string `json:"assetType,omitempty"`
}
