/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// OptionDeliverables struct for OptionDeliverables
type OptionDeliverables struct {
	Symbol string `json:"symbol,omitempty"`
	AssetType string `json:"assetType,omitempty"`
	DeliverableUnits string `json:"deliverableUnits,omitempty"`
	CurrencyType string `json:"currencyType,omitempty"`
}
