/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Future struct for Future
type Future struct {
	AskId string `json:"askId,omitempty"`
	AskPriceInDouble float32 `json:"askPriceInDouble,omitempty"`
	BidId string `json:"bidId,omitempty"`
	BidPriceInDouble float32 `json:"bidPriceInDouble,omitempty"`
	ChangeInDouble float32 `json:"changeInDouble,omitempty"`
	ClosePriceInDouble float32 `json:"closePriceInDouble,omitempty"`
	Description string `json:"description,omitempty"`
	Exchange string `json:"exchange,omitempty"`
	ExchangeName string `json:"exchangeName,omitempty"`
	FutureActiveSymbol string `json:"futureActiveSymbol,omitempty"`
	FutureExpirationDate string `json:"futureExpirationDate,omitempty"`
	FutureIsActive bool `json:"futureIsActive,omitempty"`
	FutureIsTradable bool `json:"futureIsTradable,omitempty"`
	FutureMultiplier float32 `json:"futureMultiplier,omitempty"`
	FuturePercentChange float32 `json:"futurePercentChange,omitempty"`
	FuturePriceFormat string `json:"futurePriceFormat,omitempty"`
	FutureSettlementPrice float32 `json:"futureSettlementPrice,omitempty"`
	FutureTradingHours string `json:"futureTradingHours,omitempty"`
	HighPriceInDouble float32 `json:"highPriceInDouble,omitempty"`
	LastId string `json:"lastId,omitempty"`
	LastPriceInDouble float32 `json:"lastPriceInDouble,omitempty"`
	LowPriceInDouble float32 `json:"lowPriceInDouble,omitempty"`
	Mark float32 `json:"mark,omitempty"`
	OpenInterest float32 `json:"openInterest,omitempty"`
	OpenPriceInDouble float32 `json:"openPriceInDouble,omitempty"`
	Product string `json:"product,omitempty"`
	SecurityStatus string `json:"securityStatus,omitempty"`
	Symbol string `json:"symbol,omitempty"`
	Tick float32 `json:"tick,omitempty"`
	TickAmount float32 `json:"tickAmount,omitempty"`
}
