/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SubscriptionKey struct for SubscriptionKey
type SubscriptionKey struct {
	Keys []SubscriptionKeyKeys `json:"keys,omitempty"`
}
