/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UpdatePreferences struct for UpdatePreferences
type UpdatePreferences struct {
	ExpressTrading bool `json:"expressTrading,omitempty"`
	DirectOptionsRouting bool `json:"directOptionsRouting,omitempty"`
	DirectEquityRouting bool `json:"directEquityRouting,omitempty"`
	DefaultEquityOrderLegInstruction string `json:"defaultEquityOrderLegInstruction,omitempty"`
	DefaultEquityOrderType string `json:"defaultEquityOrderType,omitempty"`
	DefaultEquityOrderPriceLinkType string `json:"defaultEquityOrderPriceLinkType,omitempty"`
	DefaultEquityOrderDuration string `json:"defaultEquityOrderDuration,omitempty"`
	DefaultEquityOrderMarketSession string `json:"defaultEquityOrderMarketSession,omitempty"`
	DefaultEquityQuantity int32 `json:"defaultEquityQuantity,omitempty"`
	MutualFundTaxLotMethod string `json:"mutualFundTaxLotMethod,omitempty"`
	OptionTaxLotMethod string `json:"optionTaxLotMethod,omitempty"`
	EquityTaxLotMethod string `json:"equityTaxLotMethod,omitempty"`
	DefaultAdvancedToolLaunch string `json:"defaultAdvancedToolLaunch,omitempty"`
	AuthTokenTimeout string `json:"authTokenTimeout,omitempty"`
}
