/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PriceLinkBasis the model 'PriceLinkBasis'
type PriceLinkBasis string

// List of PriceLinkBasis
const (
	MANUAL PriceLinkBasis = "MANUAL"
	BASE PriceLinkBasis = "BASE"
	TRIGGER PriceLinkBasis = "TRIGGER"
	LAST PriceLinkBasis = "LAST"
	BID PriceLinkBasis = "BID"
	ASK PriceLinkBasis = "ASK"
	ASK_BID PriceLinkBasis = "ASK_BID"
	MARK PriceLinkBasis = "MARK"
	AVERAGE PriceLinkBasis = "AVERAGE"
)
