/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InstrumentType struct for InstrumentType
type InstrumentType struct {
	AssetType AssetType `json:"assetType,omitempty"`
	Cusip string `json:"cusip,omitempty"`
	Description string `json:"description,omitempty"`
	OptionDeliverables []OptionOptionDeliverables `json:"optionDeliverables,omitempty"`
	OptionMultiplier float32 `json:"optionMultiplier,omitempty"`
	PutCall PutOrCall `json:"putCall,omitempty"`
	Symbol string `json:"symbol,omitempty"`
	Type string `json:"type,omitempty"`
	UnderlyingSymbol string `json:"underlyingSymbol,omitempty"`
	Factor float32 `json:"factor,omitempty"`
	MaturityDate string `json:"maturityDate,omitempty"`
	VariableRate float32 `json:"variableRate,omitempty"`
}
