/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ExpirationDate struct for ExpirationDate
type ExpirationDate struct {
	Date string `json:"date,omitempty"`
}
