/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UserPrincipalAccounts struct for UserPrincipalAccounts
type UserPrincipalAccounts struct {
	AccountId string `json:"accountId,omitempty"`
	Description string `json:"description,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	AccountCdDomainId string `json:"accountCdDomainId,omitempty"`
	Company string `json:"company,omitempty"`
	Segment string `json:"segment,omitempty"`
	SurrogateIds string `json:"surrogateIds,omitempty"`
	Preferences UserPrincipalPreferences `json:"preferences,omitempty"`
	Acl string `json:"acl,omitempty"`
	Authorizations UserPrincipalAuthorizations `json:"authorizations,omitempty"`
}
