/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// WatchlistWatchlistItems struct for WatchlistWatchlistItems
type WatchlistWatchlistItems struct {
	SequenceId float32 `json:"sequenceId,omitempty"`
	Quantity float32 `json:"quantity,omitempty"`
	AveragePrice float32 `json:"averagePrice,omitempty"`
	Commission float32 `json:"commission,omitempty"`
	PurchasedDate string `json:"purchasedDate,omitempty"`
	Instrument WatchlistInstrument `json:"instrument,omitempty"`
	Status string `json:"status,omitempty"`
}
