/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// OrderOrderLegCollection struct for OrderOrderLegCollection
type OrderOrderLegCollection struct {
	OrderLegType string `json:"orderLegType,omitempty"`
	LegId float32 `json:"legId,omitempty"`
	Instrument string `json:"instrument,omitempty"`
	Instruction string `json:"instruction,omitempty"`
	PositionEffect string `json:"positionEffect,omitempty"`
	Quantity float32 `json:"quantity,omitempty"`
	QuantityType string `json:"quantityType,omitempty"`
}
