/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CandleList struct for CandleList
type CandleList struct {
	Candles []CandleListCandles `json:"candles,omitempty"`
	Empty bool `json:"empty,omitempty"`
	Symbol string `json:"symbol,omitempty"`
}
