/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// OptionChain struct for OptionChain
type OptionChain struct {
	Symbol string `json:"symbol,omitempty"`
	Status string `json:"status,omitempty"`
	Underlying OptionChainUnderlying `json:"underlying,omitempty"`
	Strategy string `json:"strategy,omitempty"`
	Interval float32 `json:"interval,omitempty"`
	IsDelayed bool `json:"isDelayed,omitempty"`
	IsIndex bool `json:"isIndex,omitempty"`
	DaysToExpiration float32 `json:"daysToExpiration,omitempty"`
	InterestRate float32 `json:"interestRate,omitempty"`
	UnderlyingPrice float32 `json:"underlyingPrice,omitempty"`
	Volatility float32 `json:"volatility,omitempty"`
	CallExpDateMap string `json:"callExpDateMap,omitempty"`
	PutExpDateMap string `json:"putExpDateMap,omitempty"`
}
