/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UpdateWatchlist struct for UpdateWatchlist
type UpdateWatchlist struct {
	Name string `json:"name,omitempty"`
	WatchlistId string `json:"watchlistId,omitempty"`
	WatchlistItems []UpdateWatchlistWatchlistItems `json:"watchlistItems,omitempty"`
}
