/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ExecutionExecutionLegs struct for ExecutionExecutionLegs
type ExecutionExecutionLegs struct {
	LegId float32 `json:"legId,omitempty"`
	MismarkedQuantity float32 `json:"mismarkedQuantity,omitempty"`
	Price float32 `json:"price,omitempty"`
	Quantity float32 `json:"quantity,omitempty"`
	Time string `json:"time,omitempty"`
}
