/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TransactionTransactionItem struct for TransactionTransactionItem
type TransactionTransactionItem struct {
	AccountId float32 `json:"accountId,omitempty"`
	Amount float32 `json:"amount,omitempty"`
	Cost float32 `json:"cost,omitempty"`
	Instruction Instruction `json:"instruction,omitempty"`
	Instrument TransactionTransactionItemInstrument `json:"instrument,omitempty"`
	ParentChildIndicator string `json:"parentChildIndicator,omitempty"`
	ParentOrderKey float32 `json:"parentOrderKey,omitempty"`
	PositionEffect PositionEffect `json:"positionEffect,omitempty"`
	Price float32 `json:"price,omitempty"`
}
