/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Watchlist struct for Watchlist
type Watchlist struct {
	Name string `json:"name,omitempty"`
	WatchlistId string `json:"watchlistId,omitempty"`
	AccountId string `json:"accountId,omitempty"`
	Status string `json:"status,omitempty"`
	WatchlistItems []WatchlistWatchlistItems `json:"watchlistItems,omitempty"`
}
