/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PutOrCall the model 'PutOrCall'
type PutOrCall string

// List of PutOrCall
const (
	PUTORCALL_PUT PutOrCall = "PUT"
	PUTORCALL_CALL PutOrCall = "CALL"
	PUTORCALL_ALL PutOrCall = "ALL"
)
