/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CashAccount struct for CashAccount
type CashAccount struct {
	Type string `json:"type,omitempty"`
	AccountId string `json:"accountId,omitempty"`
	RoundTrips float32 `json:"roundTrips,omitempty"`
	IsDayTrader bool `json:"isDayTrader,omitempty"`
	IsClosingOnlyRestricted bool `json:"isClosingOnlyRestricted,omitempty"`
	Positions []CashAccountPositions `json:"positions,omitempty"`
	OrderStrategies []CashAccountOrderStrategies `json:"orderStrategies,omitempty"`
	InitialBalances CashAccountInitialBalances `json:"initialBalances,omitempty"`
	CurrentBalances CashAccountCurrentBalances `json:"currentBalances,omitempty"`
	ProjectedBalances CashAccountCurrentBalances `json:"projectedBalances,omitempty"`
}
