/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PriceLinkBasis the model 'PriceLinkBasis'
type PriceLinkBasis string

// List of PriceLinkBasis
const (
	PRICELINKBASIS_MANUAL PriceLinkBasis = "MANUAL"
	PRICELINKBASIS_BASE PriceLinkBasis = "BASE"
	PRICELINKBASIS_TRIGGER PriceLinkBasis = "TRIGGER"
	PRICELINKBASIS_LAST PriceLinkBasis = "LAST"
	PRICELINKBASIS_BID PriceLinkBasis = "BID"
	PRICELINKBASIS_ASK PriceLinkBasis = "ASK"
	PRICELINKBASIS_ASK_BID PriceLinkBasis = "ASK_BID"
	PRICELINKBASIS_MARK PriceLinkBasis = "MARK"
	PRICELINKBASIS_AVERAGE PriceLinkBasis = "AVERAGE"
)
