/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Session the model 'Session'
type Session string

// List of Session
const (
	SESSION_NORMAL Session = "NORMAL"
	SESSION_SEAMLESS Session = "SEAMLESS"
	SESSION_AM Session = "AM"
	SESSION_PM Session = "PM"
)
