/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SavedOrderOrderLegCollection struct for SavedOrderOrderLegCollection
type SavedOrderOrderLegCollection struct {
	OrderLegType AssetType `json:"orderLegType,omitempty"`
	LegId float32 `json:"legId,omitempty"`
	Instrument InstrumentType `json:"instrument,omitempty"`
	Instruction Instruction `json:"instruction,omitempty"`
	PositionEffect PositionEffect `json:"positionEffect,omitempty"`
	Quantity float32 `json:"quantity,omitempty"`
	QuantityType QuantityType `json:"quantityType,omitempty"`
}
