/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Strategy the model 'Strategy'
type Strategy string

// List of Strategy
const (
	SINGLE Strategy = "SINGLE"
	ANALYTICAL Strategy = "ANALYTICAL"
	COVERED Strategy = "COVERED"
	VERTICAL Strategy = "VERTICAL"
	CALENDAR Strategy = "CALENDAR"
	STRANGLE Strategy = "STRANGLE"
	STRADDLE Strategy = "STRADDLE"
	BUTTERFLY Strategy = "BUTTERFLY"
	CONDOR Strategy = "CONDOR"
	DIAGONAL Strategy = "DIAGONAL"
	COLLAR Strategy = "COLLAR"
	ROLL Strategy = "ROLL"
)
