/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Duration the model 'Duration'
type Duration string

// List of Duration
const (
	DAY Duration = "DAY"
	GOOD_TILL_CANCEL Duration = "GOOD_TILL_CANCEL"
	FILL_OR_KILL Duration = "FILL_OR_KILL"
)
