/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@protonmail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PriceLinkBasis the model 'PriceLinkBasis'
type PriceLinkBasis string

// List of PriceLinkBasis
const (
	PRICELINKBASIS_MANUAL PriceLinkBasis = "MANUAL"
	PRICELINKBASIS_BASE PriceLinkBasis = "BASE"
	PRICELINKBASIS_TRIGGER PriceLinkBasis = "TRIGGER"
	PRICELINKBASIS_LAST PriceLinkBasis = "LAST"
	PRICELINKBASIS_BID PriceLinkBasis = "BID"
	PRICELINKBASIS_ASK PriceLinkBasis = "ASK"
	PRICELINKBASIS_ASK_BID PriceLinkBasis = "ASK_BID"
	PRICELINKBASIS_MARK PriceLinkBasis = "MARK"
	PRICELINKBASIS_AVERAGE PriceLinkBasis = "AVERAGE"
)

func (v *PriceLinkBasis) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PriceLinkBasis(value)
	for _, existing := range []PriceLinkBasis{ "MANUAL", "BASE", "TRIGGER", "LAST", "BID", "ASK", "ASK_BID", "MARK", "AVERAGE",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PriceLinkBasis", value)
}

// Ptr returns reference to PriceLinkBasis value
func (v PriceLinkBasis) Ptr() *PriceLinkBasis {
	return &v
}

type NullablePriceLinkBasis struct {
	value *PriceLinkBasis
	isSet bool
}

func (v NullablePriceLinkBasis) Get() *PriceLinkBasis {
	return v.value
}

func (v *NullablePriceLinkBasis) Set(val *PriceLinkBasis) {
	v.value = val
	v.isSet = true
}

func (v NullablePriceLinkBasis) IsSet() bool {
	return v.isSet
}

func (v *NullablePriceLinkBasis) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePriceLinkBasis(val *PriceLinkBasis) *NullablePriceLinkBasis {
	return &NullablePriceLinkBasis{value: val, isSet: true}
}

func (v NullablePriceLinkBasis) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePriceLinkBasis) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

