/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@protonmail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Bond struct for Bond
type Bond struct {
	AssetType *AssetType `json:"assetType,omitempty"`
	BondPrice *float32 `json:"bondPrice,omitempty"`
	Cusip *string `json:"cusip,omitempty"`
	Description *string `json:"description,omitempty"`
	Exchange *string `json:"exchange,omitempty"`
	Symbol *string `json:"symbol,omitempty"`
}

// NewBond instantiates a new Bond object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBond() *Bond {
	this := Bond{}
	return &this
}

// NewBondWithDefaults instantiates a new Bond object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBondWithDefaults() *Bond {
	this := Bond{}
	return &this
}

// GetAssetType returns the AssetType field value if set, zero value otherwise.
func (o *Bond) GetAssetType() AssetType {
	if o == nil || o.AssetType == nil {
		var ret AssetType
		return ret
	}
	return *o.AssetType
}

// GetAssetTypeOk returns a tuple with the AssetType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bond) GetAssetTypeOk() (*AssetType, bool) {
	if o == nil || o.AssetType == nil {
		return nil, false
	}
	return o.AssetType, true
}

// HasAssetType returns a boolean if a field has been set.
func (o *Bond) HasAssetType() bool {
	if o != nil && o.AssetType != nil {
		return true
	}

	return false
}

// SetAssetType gets a reference to the given AssetType and assigns it to the AssetType field.
func (o *Bond) SetAssetType(v AssetType) {
	o.AssetType = &v
}

// GetBondPrice returns the BondPrice field value if set, zero value otherwise.
func (o *Bond) GetBondPrice() float32 {
	if o == nil || o.BondPrice == nil {
		var ret float32
		return ret
	}
	return *o.BondPrice
}

// GetBondPriceOk returns a tuple with the BondPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bond) GetBondPriceOk() (*float32, bool) {
	if o == nil || o.BondPrice == nil {
		return nil, false
	}
	return o.BondPrice, true
}

// HasBondPrice returns a boolean if a field has been set.
func (o *Bond) HasBondPrice() bool {
	if o != nil && o.BondPrice != nil {
		return true
	}

	return false
}

// SetBondPrice gets a reference to the given float32 and assigns it to the BondPrice field.
func (o *Bond) SetBondPrice(v float32) {
	o.BondPrice = &v
}

// GetCusip returns the Cusip field value if set, zero value otherwise.
func (o *Bond) GetCusip() string {
	if o == nil || o.Cusip == nil {
		var ret string
		return ret
	}
	return *o.Cusip
}

// GetCusipOk returns a tuple with the Cusip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bond) GetCusipOk() (*string, bool) {
	if o == nil || o.Cusip == nil {
		return nil, false
	}
	return o.Cusip, true
}

// HasCusip returns a boolean if a field has been set.
func (o *Bond) HasCusip() bool {
	if o != nil && o.Cusip != nil {
		return true
	}

	return false
}

// SetCusip gets a reference to the given string and assigns it to the Cusip field.
func (o *Bond) SetCusip(v string) {
	o.Cusip = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Bond) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bond) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Bond) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Bond) SetDescription(v string) {
	o.Description = &v
}

// GetExchange returns the Exchange field value if set, zero value otherwise.
func (o *Bond) GetExchange() string {
	if o == nil || o.Exchange == nil {
		var ret string
		return ret
	}
	return *o.Exchange
}

// GetExchangeOk returns a tuple with the Exchange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bond) GetExchangeOk() (*string, bool) {
	if o == nil || o.Exchange == nil {
		return nil, false
	}
	return o.Exchange, true
}

// HasExchange returns a boolean if a field has been set.
func (o *Bond) HasExchange() bool {
	if o != nil && o.Exchange != nil {
		return true
	}

	return false
}

// SetExchange gets a reference to the given string and assigns it to the Exchange field.
func (o *Bond) SetExchange(v string) {
	o.Exchange = &v
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *Bond) GetSymbol() string {
	if o == nil || o.Symbol == nil {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bond) GetSymbolOk() (*string, bool) {
	if o == nil || o.Symbol == nil {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *Bond) HasSymbol() bool {
	if o != nil && o.Symbol != nil {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *Bond) SetSymbol(v string) {
	o.Symbol = &v
}

func (o Bond) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AssetType != nil {
		toSerialize["assetType"] = o.AssetType
	}
	if o.BondPrice != nil {
		toSerialize["bondPrice"] = o.BondPrice
	}
	if o.Cusip != nil {
		toSerialize["cusip"] = o.Cusip
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Exchange != nil {
		toSerialize["exchange"] = o.Exchange
	}
	if o.Symbol != nil {
		toSerialize["symbol"] = o.Symbol
	}
	return json.Marshal(toSerialize)
}

type NullableBond struct {
	value *Bond
	isSet bool
}

func (v NullableBond) Get() *Bond {
	return v.value
}

func (v *NullableBond) Set(val *Bond) {
	v.value = val
	v.isSet = true
}

func (v NullableBond) IsSet() bool {
	return v.isSet
}

func (v *NullableBond) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBond(val *Bond) *NullableBond {
	return &NullableBond{value: val, isSet: true}
}

func (v NullableBond) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBond) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


