/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@protonmail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// OrderStrategyType the model 'OrderStrategyType'
type OrderStrategyType string

// List of OrderStrategyType
const (
	ORDERSTRATEGYTYPE_SINGLE OrderStrategyType = "SINGLE"
	ORDERSTRATEGYTYPE_OCO OrderStrategyType = "OCO"
	ORDERSTRATEGYTYPE_TRIGGER OrderStrategyType = "TRIGGER"
)

func (v *OrderStrategyType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OrderStrategyType(value)
	for _, existing := range []OrderStrategyType{ "SINGLE", "OCO", "TRIGGER",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OrderStrategyType", value)
}

// Ptr returns reference to OrderStrategyType value
func (v OrderStrategyType) Ptr() *OrderStrategyType {
	return &v
}

type NullableOrderStrategyType struct {
	value *OrderStrategyType
	isSet bool
}

func (v NullableOrderStrategyType) Get() *OrderStrategyType {
	return v.value
}

func (v *NullableOrderStrategyType) Set(val *OrderStrategyType) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderStrategyType) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderStrategyType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderStrategyType(val *OrderStrategyType) *NullableOrderStrategyType {
	return &NullableOrderStrategyType{value: val, isSet: true}
}

func (v NullableOrderStrategyType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderStrategyType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

