/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@protonmail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// OptionChain struct for OptionChain
type OptionChain struct {
	CallExpDateMap *string `json:"callExpDateMap,omitempty"`
	DaysToExpiration *float32 `json:"daysToExpiration,omitempty"`
	InterestRate *float32 `json:"interestRate,omitempty"`
	Interval *float32 `json:"interval,omitempty"`
	IsDelayed *bool `json:"isDelayed,omitempty"`
	IsIndex *bool `json:"isIndex,omitempty"`
	PutExpDateMap *string `json:"putExpDateMap,omitempty"`
	Status *OrderStatus `json:"status,omitempty"`
	Strategy *Strategy `json:"strategy,omitempty"`
	Symbol *string `json:"symbol,omitempty"`
	Underlying *OptionChainUnderlying `json:"underlying,omitempty"`
	UnderlyingPrice *float32 `json:"underlyingPrice,omitempty"`
	Volatility *float32 `json:"volatility,omitempty"`
}

// NewOptionChain instantiates a new OptionChain object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOptionChain() *OptionChain {
	this := OptionChain{}
	return &this
}

// NewOptionChainWithDefaults instantiates a new OptionChain object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOptionChainWithDefaults() *OptionChain {
	this := OptionChain{}
	return &this
}

// GetCallExpDateMap returns the CallExpDateMap field value if set, zero value otherwise.
func (o *OptionChain) GetCallExpDateMap() string {
	if o == nil || o.CallExpDateMap == nil {
		var ret string
		return ret
	}
	return *o.CallExpDateMap
}

// GetCallExpDateMapOk returns a tuple with the CallExpDateMap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionChain) GetCallExpDateMapOk() (*string, bool) {
	if o == nil || o.CallExpDateMap == nil {
		return nil, false
	}
	return o.CallExpDateMap, true
}

// HasCallExpDateMap returns a boolean if a field has been set.
func (o *OptionChain) HasCallExpDateMap() bool {
	if o != nil && o.CallExpDateMap != nil {
		return true
	}

	return false
}

// SetCallExpDateMap gets a reference to the given string and assigns it to the CallExpDateMap field.
func (o *OptionChain) SetCallExpDateMap(v string) {
	o.CallExpDateMap = &v
}

// GetDaysToExpiration returns the DaysToExpiration field value if set, zero value otherwise.
func (o *OptionChain) GetDaysToExpiration() float32 {
	if o == nil || o.DaysToExpiration == nil {
		var ret float32
		return ret
	}
	return *o.DaysToExpiration
}

// GetDaysToExpirationOk returns a tuple with the DaysToExpiration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionChain) GetDaysToExpirationOk() (*float32, bool) {
	if o == nil || o.DaysToExpiration == nil {
		return nil, false
	}
	return o.DaysToExpiration, true
}

// HasDaysToExpiration returns a boolean if a field has been set.
func (o *OptionChain) HasDaysToExpiration() bool {
	if o != nil && o.DaysToExpiration != nil {
		return true
	}

	return false
}

// SetDaysToExpiration gets a reference to the given float32 and assigns it to the DaysToExpiration field.
func (o *OptionChain) SetDaysToExpiration(v float32) {
	o.DaysToExpiration = &v
}

// GetInterestRate returns the InterestRate field value if set, zero value otherwise.
func (o *OptionChain) GetInterestRate() float32 {
	if o == nil || o.InterestRate == nil {
		var ret float32
		return ret
	}
	return *o.InterestRate
}

// GetInterestRateOk returns a tuple with the InterestRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionChain) GetInterestRateOk() (*float32, bool) {
	if o == nil || o.InterestRate == nil {
		return nil, false
	}
	return o.InterestRate, true
}

// HasInterestRate returns a boolean if a field has been set.
func (o *OptionChain) HasInterestRate() bool {
	if o != nil && o.InterestRate != nil {
		return true
	}

	return false
}

// SetInterestRate gets a reference to the given float32 and assigns it to the InterestRate field.
func (o *OptionChain) SetInterestRate(v float32) {
	o.InterestRate = &v
}

// GetInterval returns the Interval field value if set, zero value otherwise.
func (o *OptionChain) GetInterval() float32 {
	if o == nil || o.Interval == nil {
		var ret float32
		return ret
	}
	return *o.Interval
}

// GetIntervalOk returns a tuple with the Interval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionChain) GetIntervalOk() (*float32, bool) {
	if o == nil || o.Interval == nil {
		return nil, false
	}
	return o.Interval, true
}

// HasInterval returns a boolean if a field has been set.
func (o *OptionChain) HasInterval() bool {
	if o != nil && o.Interval != nil {
		return true
	}

	return false
}

// SetInterval gets a reference to the given float32 and assigns it to the Interval field.
func (o *OptionChain) SetInterval(v float32) {
	o.Interval = &v
}

// GetIsDelayed returns the IsDelayed field value if set, zero value otherwise.
func (o *OptionChain) GetIsDelayed() bool {
	if o == nil || o.IsDelayed == nil {
		var ret bool
		return ret
	}
	return *o.IsDelayed
}

// GetIsDelayedOk returns a tuple with the IsDelayed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionChain) GetIsDelayedOk() (*bool, bool) {
	if o == nil || o.IsDelayed == nil {
		return nil, false
	}
	return o.IsDelayed, true
}

// HasIsDelayed returns a boolean if a field has been set.
func (o *OptionChain) HasIsDelayed() bool {
	if o != nil && o.IsDelayed != nil {
		return true
	}

	return false
}

// SetIsDelayed gets a reference to the given bool and assigns it to the IsDelayed field.
func (o *OptionChain) SetIsDelayed(v bool) {
	o.IsDelayed = &v
}

// GetIsIndex returns the IsIndex field value if set, zero value otherwise.
func (o *OptionChain) GetIsIndex() bool {
	if o == nil || o.IsIndex == nil {
		var ret bool
		return ret
	}
	return *o.IsIndex
}

// GetIsIndexOk returns a tuple with the IsIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionChain) GetIsIndexOk() (*bool, bool) {
	if o == nil || o.IsIndex == nil {
		return nil, false
	}
	return o.IsIndex, true
}

// HasIsIndex returns a boolean if a field has been set.
func (o *OptionChain) HasIsIndex() bool {
	if o != nil && o.IsIndex != nil {
		return true
	}

	return false
}

// SetIsIndex gets a reference to the given bool and assigns it to the IsIndex field.
func (o *OptionChain) SetIsIndex(v bool) {
	o.IsIndex = &v
}

// GetPutExpDateMap returns the PutExpDateMap field value if set, zero value otherwise.
func (o *OptionChain) GetPutExpDateMap() string {
	if o == nil || o.PutExpDateMap == nil {
		var ret string
		return ret
	}
	return *o.PutExpDateMap
}

// GetPutExpDateMapOk returns a tuple with the PutExpDateMap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionChain) GetPutExpDateMapOk() (*string, bool) {
	if o == nil || o.PutExpDateMap == nil {
		return nil, false
	}
	return o.PutExpDateMap, true
}

// HasPutExpDateMap returns a boolean if a field has been set.
func (o *OptionChain) HasPutExpDateMap() bool {
	if o != nil && o.PutExpDateMap != nil {
		return true
	}

	return false
}

// SetPutExpDateMap gets a reference to the given string and assigns it to the PutExpDateMap field.
func (o *OptionChain) SetPutExpDateMap(v string) {
	o.PutExpDateMap = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *OptionChain) GetStatus() OrderStatus {
	if o == nil || o.Status == nil {
		var ret OrderStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionChain) GetStatusOk() (*OrderStatus, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *OptionChain) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given OrderStatus and assigns it to the Status field.
func (o *OptionChain) SetStatus(v OrderStatus) {
	o.Status = &v
}

// GetStrategy returns the Strategy field value if set, zero value otherwise.
func (o *OptionChain) GetStrategy() Strategy {
	if o == nil || o.Strategy == nil {
		var ret Strategy
		return ret
	}
	return *o.Strategy
}

// GetStrategyOk returns a tuple with the Strategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionChain) GetStrategyOk() (*Strategy, bool) {
	if o == nil || o.Strategy == nil {
		return nil, false
	}
	return o.Strategy, true
}

// HasStrategy returns a boolean if a field has been set.
func (o *OptionChain) HasStrategy() bool {
	if o != nil && o.Strategy != nil {
		return true
	}

	return false
}

// SetStrategy gets a reference to the given Strategy and assigns it to the Strategy field.
func (o *OptionChain) SetStrategy(v Strategy) {
	o.Strategy = &v
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *OptionChain) GetSymbol() string {
	if o == nil || o.Symbol == nil {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionChain) GetSymbolOk() (*string, bool) {
	if o == nil || o.Symbol == nil {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *OptionChain) HasSymbol() bool {
	if o != nil && o.Symbol != nil {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *OptionChain) SetSymbol(v string) {
	o.Symbol = &v
}

// GetUnderlying returns the Underlying field value if set, zero value otherwise.
func (o *OptionChain) GetUnderlying() OptionChainUnderlying {
	if o == nil || o.Underlying == nil {
		var ret OptionChainUnderlying
		return ret
	}
	return *o.Underlying
}

// GetUnderlyingOk returns a tuple with the Underlying field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionChain) GetUnderlyingOk() (*OptionChainUnderlying, bool) {
	if o == nil || o.Underlying == nil {
		return nil, false
	}
	return o.Underlying, true
}

// HasUnderlying returns a boolean if a field has been set.
func (o *OptionChain) HasUnderlying() bool {
	if o != nil && o.Underlying != nil {
		return true
	}

	return false
}

// SetUnderlying gets a reference to the given OptionChainUnderlying and assigns it to the Underlying field.
func (o *OptionChain) SetUnderlying(v OptionChainUnderlying) {
	o.Underlying = &v
}

// GetUnderlyingPrice returns the UnderlyingPrice field value if set, zero value otherwise.
func (o *OptionChain) GetUnderlyingPrice() float32 {
	if o == nil || o.UnderlyingPrice == nil {
		var ret float32
		return ret
	}
	return *o.UnderlyingPrice
}

// GetUnderlyingPriceOk returns a tuple with the UnderlyingPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionChain) GetUnderlyingPriceOk() (*float32, bool) {
	if o == nil || o.UnderlyingPrice == nil {
		return nil, false
	}
	return o.UnderlyingPrice, true
}

// HasUnderlyingPrice returns a boolean if a field has been set.
func (o *OptionChain) HasUnderlyingPrice() bool {
	if o != nil && o.UnderlyingPrice != nil {
		return true
	}

	return false
}

// SetUnderlyingPrice gets a reference to the given float32 and assigns it to the UnderlyingPrice field.
func (o *OptionChain) SetUnderlyingPrice(v float32) {
	o.UnderlyingPrice = &v
}

// GetVolatility returns the Volatility field value if set, zero value otherwise.
func (o *OptionChain) GetVolatility() float32 {
	if o == nil || o.Volatility == nil {
		var ret float32
		return ret
	}
	return *o.Volatility
}

// GetVolatilityOk returns a tuple with the Volatility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionChain) GetVolatilityOk() (*float32, bool) {
	if o == nil || o.Volatility == nil {
		return nil, false
	}
	return o.Volatility, true
}

// HasVolatility returns a boolean if a field has been set.
func (o *OptionChain) HasVolatility() bool {
	if o != nil && o.Volatility != nil {
		return true
	}

	return false
}

// SetVolatility gets a reference to the given float32 and assigns it to the Volatility field.
func (o *OptionChain) SetVolatility(v float32) {
	o.Volatility = &v
}

func (o OptionChain) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CallExpDateMap != nil {
		toSerialize["callExpDateMap"] = o.CallExpDateMap
	}
	if o.DaysToExpiration != nil {
		toSerialize["daysToExpiration"] = o.DaysToExpiration
	}
	if o.InterestRate != nil {
		toSerialize["interestRate"] = o.InterestRate
	}
	if o.Interval != nil {
		toSerialize["interval"] = o.Interval
	}
	if o.IsDelayed != nil {
		toSerialize["isDelayed"] = o.IsDelayed
	}
	if o.IsIndex != nil {
		toSerialize["isIndex"] = o.IsIndex
	}
	if o.PutExpDateMap != nil {
		toSerialize["putExpDateMap"] = o.PutExpDateMap
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Strategy != nil {
		toSerialize["strategy"] = o.Strategy
	}
	if o.Symbol != nil {
		toSerialize["symbol"] = o.Symbol
	}
	if o.Underlying != nil {
		toSerialize["underlying"] = o.Underlying
	}
	if o.UnderlyingPrice != nil {
		toSerialize["underlyingPrice"] = o.UnderlyingPrice
	}
	if o.Volatility != nil {
		toSerialize["volatility"] = o.Volatility
	}
	return json.Marshal(toSerialize)
}

type NullableOptionChain struct {
	value *OptionChain
	isSet bool
}

func (v NullableOptionChain) Get() *OptionChain {
	return v.value
}

func (v *NullableOptionChain) Set(val *OptionChain) {
	v.value = val
	v.isSet = true
}

func (v NullableOptionChain) IsSet() bool {
	return v.isSet
}

func (v *NullableOptionChain) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOptionChain(val *OptionChain) *NullableOptionChain {
	return &NullableOptionChain{value: val, isSet: true}
}

func (v NullableOptionChain) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOptionChain) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


