/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@protonmail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PutOrCall the model 'PutOrCall'
type PutOrCall string

// List of PutOrCall
const (
	PUTORCALL_PUT PutOrCall = "PUT"
	PUTORCALL_CALL PutOrCall = "CALL"
	PUTORCALL_ALL PutOrCall = "ALL"
)

func (v *PutOrCall) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PutOrCall(value)
	for _, existing := range []PutOrCall{ "PUT", "CALL", "ALL",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PutOrCall", value)
}

// Ptr returns reference to PutOrCall value
func (v PutOrCall) Ptr() *PutOrCall {
	return &v
}

type NullablePutOrCall struct {
	value *PutOrCall
	isSet bool
}

func (v NullablePutOrCall) Get() *PutOrCall {
	return v.value
}

func (v *NullablePutOrCall) Set(val *PutOrCall) {
	v.value = val
	v.isSet = true
}

func (v NullablePutOrCall) IsSet() bool {
	return v.isSet
}

func (v *NullablePutOrCall) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutOrCall(val *PutOrCall) *NullablePutOrCall {
	return &NullablePutOrCall{value: val, isSet: true}
}

func (v NullablePutOrCall) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutOrCall) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

